services:
  postgres:
    image: postgres:16
    container_name: churn_postgres

    environment:
      POSTGRES_DB: customer_churn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: churn_redis

    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend

    container_name: churn_backend

    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend

    container_name: churn_frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend

volumes:
  postgres_data:
